### ISSUE TITLE
failed to run tum demo

### ISSUE THREAD

**Issue by ArthurHoumo** [zhangganlin/GlORIE-SLAM#2]
Start GlORIE-SLAM at 2024-07-02 06:28:19,
   scene: tumrgbd-freiburg3_office,
   only_tracking: False,
   output: output/TUM_RGBD/demo/freiburg3_office
------------------------------
[INFO] Load droid pretrained checkpiont from ./pretrained/droid.pth!
[INFO] Load ConvONet pretrained checkpiont from ./pretrained/middle_fine.pt!
[MAPPER] Mapping Triggered!
[TRACKER] Tracking Triggered!
[TRACKER] : 100%|███████████████████████████████████████████████████████████████████| 100/100 [00:02<00:00, 33.54it/s]
[TRACKER] Tracking Done!
[MAPPER] Mapping Done!
[TRACKER] Final Global BA Triggered!
[TRACKER] Final Global BA Done!
[POINTCLOUD] Updating pointcloud position ...
[MAPPER] Number of pixels with valid droid depth: 174123/196608 (88.56%)
Process Process-3:
Traceback (most recent call last):
  File "/root/miniconda3/envs/glorie-slam/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/miniconda3/envs/glorie-slam/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/Arthur/open-projects/GlORIE-SLAM/src/slam.py", line 116, in mapping
    self.terminate()
  File "/data/Arthur/open-projects/GlORIE-SLAM/src/slam.py", line 135, in terminate
    self.mapper.final_refine(save_final_pcl=True)
  File "/data/Arthur/open-projects/GlORIE-SLAM/src/mapper.py", line 835, in final_refine
    self.mapping_keyframe(idx,video_idx,mono_depth,outer_joint_iters,num_joint_iters,
  File "/data/Arthur/open-projects/GlORIE-SLAM/src/mapper.py", line 719, in mapping_keyframe
    self.dynamic_r_add = self.dynamic_r_add/3.0 * anchor_depth
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
------------------------------
GlORIE-SLAM finishes!
+Style.RESET_ALL+2024-07-02 06:28:31

**Comment by zhangganlin** [comment]
Hi,

Thanks for pointing out the bug. It is because that in the tum-rgbd demo config, only the first 200 frames are used for simplicity (since it is just a demo config, only aim to give users a brief idea how our system works), which are not enough for the bootstrapping for the tracker, thus actually no frame is used for mapping (the mapper has not started yet), so in the refinement step in mapper, it cannot find any stored information about the dynamic_r. 

Now I have updated the config to use the first 400 frames so that there are enough frames for the tracker for bootstrapping and it should work now.
