### ISSUE TITLE
run with custom datasets

### ISSUE THREAD

**Issue by cv-lab-x** [zhangganlin/GlORIE-SLAM#3]
hi, thanks for your great work, could your give some advices or configs to run with custom datasets ?
Looking forward  to your reply, thansk. @zhangganlin

**Comment by zhangganlin** [comment]
Hi,

For custom datasets, you can check the configs of ScanNet and TUM-RGBD, since both of these datasets are real world datasets, they should be similar to the custom datasets' setting (remember to change the intrinsic parameters). 

Also, You can try with the *only_tracking* setting first to make sure to adjust the parameters of the tracker to a proper state. For the mapper, there is no need to adjust much. 

Personally I haven't tried with custom datasets but I think it would not be much different for the config.
Let me know if there are other issues.

Best
Ganlin
