### ISSUE TITLE
About performance reproduction

### ISSUE THREAD

**Issue by Ysc-shark** [zhangganlin/GlORIE-SLAM#5]
Hi, thank you for your excellent work.

I have a few questions regarding performance reproduction. I used the provided config:_configs/TUM_RGBD/freiburg3_office.yaml_ to run the code on the TUM fr3/office dataset, and the Full Trajectory results are as follows. 
![image](https://github.com/user-attachments/assets/537585fc-2eb8-41fc-8a85-026c02e3a85e)

 Could you please explain how to calculate the reported ATE RMSE 1.44? Also, what does the scale refer to in this context?

Additionally, I would like to ask if I want to run SLAM on different datasets, should I adopt the Key Frames rendering performance or the Every 5 Frames rendering performance?

Thank you in advance for your help!

**Comment by zhangganlin** [comment]
Hi, 

This is because that the tracking part of glorie-slam partly use cuda code for bundle adjustment (which is inherited from Droid-SLAM), due to the parallelism of this part of cuda code, even if we have already manully fixed the random seed in python, there can still be some difference among each run. 

For Key Frame rendering and every 5 frames rendering, the ''keyframe'' one evaulates on the frames which we used to do mapping, and ''every 5 frames'' one evaluates on every 5 frames regardless whether it is used for mapping.  As far as I know, some paper reports both results, and in most cases, if they did not say which frames are used for rendering evaluation explicitly, the "keyframe" one is used.

**Comment by Ysc-shark** [comment]
Thanks for your reply.
I noticed that some GS-based SLAM papers use different methods to evaluate tracking and rendering, such as every 5 frames without keyframes.
